-- DEPRECATED for the shared Letus Supabase project.
--
-- Do NOT apply this file onto jrnabzfvdcmcoxyadmax — it uses uuid PKs and
-- clashes with Letus user_economy (user_id text).
--
-- Production path: apply supabase/supro_on_letus.sql instead.
-- This file is retained only as historical reference for isolated experiments.
